name: oci-terraform-gitactions-demo
on:
  push:
    branches:
      - main
jobs:
  build-with-terraform:
    name: Build With Terraform
    runs-on: ubuntu-latest
    env:
      TF_VAR_tenancy_ocid: ${{secrets.TENANCY_OCID}}
      TF_VAR_compartment_ocid: ${{secrets.COMPARTMENT_OCID}}
      TF_VAR_user_ocid: ${{secrets.USER_OCID}}
      TF_VAR_private_key_path: ${{secrets.PRIVATE_KEY_PATH}}
      TF_VAR_private_key: ${{secrets.PRIVATE_KEY}}
      TF_VAR_fingerprint: ${{secrets.FINGERPRINT}}
      TF_VAR_region: ${{secrets.REGION}}
      TF_VAR_bucket_name: "gitactions_bucket"
      
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: 'Init Terraform'
        id: init
        run: terraform init 

      - name: 'Validate Terraform'
        id: validate
        run: terraform validate
      
      - name: 'Terraform Plan'
        id: plan 
        run: terraform plan
        continue-on-error: false

      - name: 'Terraform Apply'
        id: apply 
        run: terraform apply -auto-approve
